name: Spread tests
on:
  schedule:
    # Weekly sunday testing for bitrot
    - cron: '0 12 * * 0'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Cleanup job workspace
        id: cleanup-job-workspace
        run: |
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"
      - uses: actions/checkout@v2

      - name: Build snap
        run: |
          spread -artifacts=./artifacts google-nested:tests/spread/build/build-snap
          find ./artifacts -type f -name "*.artifact" -exec cp {} "${{ github.workspace }}" \;

      - uses: actions/upload-artifact@v2
        with:
          name: core-snap
          path: "${{ github.workspace }}/core22.artifact"

      - uses: actions/checkout@v3
        with:
          repository: 'valentindavid/core-initrd'
          ref: aa0f1c41afd57e02f31c9fb76d39f54557d727fe
          path: core-initrd

      - name: Build core-initrd
        run: |
          spread -artifacts=./artifacts-initrd google-nested:tests/spread/build/build-initrd
          find artifacts-initrd -name pc-kernel.snap -exec mv {} . ";"

      - uses: actions/upload-artifact@v2
        with:
          name: core-initrd
          path: "${{ github.workspace }}/pc-kernel.snap"

      - name: Discard spread workers
        if: always()
        run: |
          shopt -s nullglob
          for r in .spread-reuse.*.yaml; do
            spread -discard -reuse-pid="$(echo "$r" | grep -o -E '[0-9]+')"
          done

  tests-main:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Cleanup job workspace
        id: cleanup-job-workspace
        run: |
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: core-snap
          path: "${{ github.workspace }}/core22.artifact"
      
      - name: Run tests
        run: |
          spread google-nested:tests/spread/main/

      - name: Discard spread workers
        if: always()
        run: |
          shopt -s nullglob
          for r in .spread-reuse.*.yaml; do
            spread -discard -reuse-pid="$(echo "$r" | grep -o -E '[0-9]+')"
          done
  tests-snapd:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Cleanup job workspace
        id: cleanup-job-workspace
        run: |
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"
      
      - uses: actions/checkout@v2
        with:
          path: core-base
      - uses: actions/checkout@v3
        with:
          repository: 'snapcore/snapd'
          path: snapd
          ref: 4f88cb8d5798723b135b607e533ba59b6f878a68
      - uses: actions/download-artifact@v2
        with:
          name: core-snap
      
      - uses: actions/download-artifact@v2
        with:
          name: core-initrd

      - name: Install spread
        run: curl -s https://storage.googleapis.com/snapd-spread-tests/spread/spread-amd64.tar.gz | sudo tar xzv -C /usr/bin

      - name: Build image
        working-directory: '${{ github.workspace }}'
        run: |
          . "core-base/tests/lib/prepare-utils.sh"

          echo "************* DOWNLOADING SNAPS *************"
          download_core22_snaps 'edge'

          echo "************* INSTALLING DEPS *************"
          install_core22_deps

          echo "************* WRITING CLOUD-INIT CONFIG *************"
          prepare_core22_cloudinit

          echo "************* BUILDING CORE22 IMAGE *************"
          uc_snap="$(get_core_snap_name)"
          mv core22.artifact "$uc_snap"
          build_core22_image

          echo "************* STARTING CORE22 VM *************"
          start_snapd_core_vm '${{ github.workspace }}'

          cd snapd
          
          # add any test suites that should be tested here
          SPREAD_EXTERNAL_ADDRESS=localhost:8022 spread external:ubuntu-core-22-64:tests/smoke/ external:ubuntu-core-22-64:tests/core/

      - name: Discard spread workers
        if: always()
        run: |
          shopt -s nullglob
          for r in .spread-reuse.*.yaml; do
            spread -discard -reuse-pid="$(echo "$r" | grep -o -E '[0-9]+')"
          done

